/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 40
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 31
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_EQ = 1,
  anon_sym_PLUS_EQ = 2,
  anon_sym_SEMI = 3,
  anon_sym_DOT = 4,
  anon_sym_LBRACE = 5,
  anon_sym_RBRACE = 6,
  anon_sym_LPAREN = 7,
  anon_sym_RPAREN = 8,
  anon_sym_COMMA = 9,
  sym__quoted_string = 10,
  sym__non_quoted_string = 11,
  sym_wildcard = 12,
  sym_identifier_segment = 13,
  sym__link_string = 14,
  sym_comment = 15,
  sym_source_file = 16,
  sym_pair = 17,
  sym_inner_pair = 18,
  sym_key = 19,
  sym__value = 20,
  sym_dictionary = 21,
  sym_list = 22,
  sym__elements = 23,
  sym_string = 24,
  sym_wildcard_string = 25,
  sym__wildcard_segment = 26,
  aux_sym_source_file_repeat1 = 27,
  aux_sym_dictionary_repeat1 = 28,
  aux_sym__elements_repeat1 = 29,
  aux_sym_wildcard_string_repeat1 = 30,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_EQ] = "=",
  [anon_sym_PLUS_EQ] = "+=",
  [anon_sym_SEMI] = ";",
  [anon_sym_DOT] = ".",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [sym__quoted_string] = "_quoted_string",
  [sym__non_quoted_string] = "_non_quoted_string",
  [sym_wildcard] = "wildcard",
  [sym_identifier_segment] = "identifier_segment",
  [sym__link_string] = "_link_string",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_pair] = "pair",
  [sym_inner_pair] = "inner_pair",
  [sym_key] = "key",
  [sym__value] = "_value",
  [sym_dictionary] = "dictionary",
  [sym_list] = "list",
  [sym__elements] = "_elements",
  [sym_string] = "string",
  [sym_wildcard_string] = "wildcard_string",
  [sym__wildcard_segment] = "_wildcard_segment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_dictionary_repeat1] = "dictionary_repeat1",
  [aux_sym__elements_repeat1] = "_elements_repeat1",
  [aux_sym_wildcard_string_repeat1] = "wildcard_string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_PLUS_EQ] = anon_sym_PLUS_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym__quoted_string] = sym__quoted_string,
  [sym__non_quoted_string] = sym__non_quoted_string,
  [sym_wildcard] = sym_wildcard,
  [sym_identifier_segment] = sym_identifier_segment,
  [sym__link_string] = sym__link_string,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_pair] = sym_pair,
  [sym_inner_pair] = sym_inner_pair,
  [sym_key] = sym_key,
  [sym__value] = sym__value,
  [sym_dictionary] = sym_dictionary,
  [sym_list] = sym_list,
  [sym__elements] = sym__elements,
  [sym_string] = sym_string,
  [sym_wildcard_string] = sym_wildcard_string,
  [sym__wildcard_segment] = sym__wildcard_segment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_dictionary_repeat1] = aux_sym_dictionary_repeat1,
  [aux_sym__elements_repeat1] = aux_sym__elements_repeat1,
  [aux_sym_wildcard_string_repeat1] = aux_sym_wildcard_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym__quoted_string] = {
    .visible = false,
    .named = true,
  },
  [sym__non_quoted_string] = {
    .visible = false,
    .named = true,
  },
  [sym_wildcard] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier_segment] = {
    .visible = true,
    .named = true,
  },
  [sym__link_string] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_inner_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_dictionary] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym__elements] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_wildcard_string] = {
    .visible = true,
    .named = true,
  },
  [sym__wildcard_segment] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dictionary_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__elements_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_wildcard_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_assignment = 1,
  field_name = 2,
  field_realm = 3,
  field_stage = 4,
  field_value = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_assignment] = "assignment",
  [field_name] = "name",
  [field_realm] = "realm",
  [field_stage] = "stage",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_assignment, 1},
    {field_value, 2},
  [2] =
    {field_name, 4},
    {field_realm, 2},
    {field_stage, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
};

static const TSCharacterRange sym__non_quoted_string_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '"'}, {'$', '\''}, {'*', '*'}, {'-', '-'}, {'/', ':'}, {'<', '<'},
  {'>', 'z'}, {'|', '|'}, {'~', 0x10ffff},
};

static const TSCharacterRange sym__link_string_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '"'}, {'$', '\''}, {'*', '*'}, {'-', ':'}, {'<', '<'}, {'>', 'z'},
  {'|', '|'}, {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '"', 21,
        '#', 33,
        '(', 14,
        ')', 15,
        '*', 29,
        '+', 4,
        ',', 16,
        '.', 11,
        ';', 10,
        '=', 8,
        '@', 23,
        '\\', 26,
        '{', 12,
        '}', 13,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      if (lookahead != 0) ADVANCE(25);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 21,
        '#', 33,
        '(', 14,
        ')', 15,
        '@', 23,
        '\\', 26,
        '{', 12,
        '}', 13,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (lookahead != 0 &&
          lookahead != '+' &&
          lookahead != ',' &&
          lookahead != '.' &&
          lookahead != ';' &&
          lookahead != '=') ADVANCE(25);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 4:
      if (lookahead == '=') ADVANCE(9);
      END_STATE();
    case 5:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '"', 21,
        '#', 33,
        '(', 14,
        ')', 15,
        '*', 29,
        '+', 4,
        ',', 16,
        ';', 10,
        '=', 8,
        '@', 23,
        '\\', 26,
        '{', 12,
        '}', 13,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      if (lookahead != 0 &&
          (lookahead < '(' || '.' < lookahead)) ADVANCE(25);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      if (lookahead == '#') ADVANCE(33);
      if (lookahead == '*') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_PLUS_EQ);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym__quoted_string);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym__quoted_string);
      if (lookahead == '"') ADVANCE(20);
      if (lookahead == '\\') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '#' ||
          lookahead == '(' ||
          lookahead == ')' ||
          lookahead == '+' ||
          lookahead == ',' ||
          lookahead == '.' ||
          lookahead == ';' ||
          lookahead == '=' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(2);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym__quoted_string);
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym__quoted_string);
      if (lookahead == '\\') ADVANCE(26);
      if ((!eof && set_contains(sym__non_quoted_string_character_set_1, 11, lookahead))) ADVANCE(25);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym__non_quoted_string);
      if (lookahead == '"') ADVANCE(20);
      if (lookahead == '\\') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '#' ||
          lookahead == '(' ||
          lookahead == ')' ||
          lookahead == '+' ||
          lookahead == ',' ||
          lookahead == '.' ||
          lookahead == ';' ||
          lookahead == '=' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(2);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym__non_quoted_string);
      if (lookahead == '"') ADVANCE(18);
      if (lookahead == '\\') ADVANCE(22);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym__non_quoted_string);
      if (lookahead == '.') ADVANCE(31);
      if (lookahead == '\\') ADVANCE(27);
      if ((!eof && set_contains(sym__link_string_character_set_1, 10, lookahead))) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym__non_quoted_string);
      if (lookahead == '\\') ADVANCE(26);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      if ((!eof && set_contains(sym__non_quoted_string_character_set_1, 11, lookahead))) ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym__non_quoted_string);
      if (lookahead == '\\') ADVANCE(26);
      if ((!eof && set_contains(sym__non_quoted_string_character_set_1, 11, lookahead))) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym__non_quoted_string);
      if (lookahead == '\\') ADVANCE(26);
      if (lookahead != 0) ADVANCE(25);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym__non_quoted_string);
      if (lookahead == '\\') ADVANCE(27);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_wildcard);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_wildcard);
      if (lookahead == '\\') ADVANCE(26);
      if ((!eof && set_contains(sym__non_quoted_string_character_set_1, 11, lookahead))) ADVANCE(25);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier_segment);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym__link_string);
      if (lookahead == '\\') ADVANCE(32);
      if ((!eof && set_contains(sym__link_string_character_set_1, 10, lookahead))) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym__link_string);
      if (lookahead == '\\') ADVANCE(32);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(33);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 6},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 6},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 6},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 6},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_PLUS_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym__quoted_string] = ACTIONS(1),
    [sym__non_quoted_string] = ACTIONS(1),
    [sym_wildcard] = ACTIONS(1),
    [sym_identifier_segment] = ACTIONS(1),
    [sym__link_string] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(35),
    [sym_pair] = STATE(12),
    [sym_key] = STATE(31),
    [sym__wildcard_segment] = STATE(34),
    [aux_sym_source_file_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_wildcard] = ACTIONS(7),
    [sym_identifier_segment] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_RPAREN,
    STATE(36), 1,
      sym__elements,
    ACTIONS(15), 3,
      sym__quoted_string,
      sym__non_quoted_string,
      sym__link_string,
    STATE(19), 4,
      sym__value,
      sym_dictionary,
      sym_list,
      sym_string,
  [27] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_RPAREN,
    ACTIONS(15), 3,
      sym__quoted_string,
      sym__non_quoted_string,
      sym__link_string,
    STATE(32), 4,
      sym__value,
      sym_dictionary,
      sym_list,
      sym_string,
  [51] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_RPAREN,
    ACTIONS(15), 3,
      sym__quoted_string,
      sym__non_quoted_string,
      sym__link_string,
    STATE(32), 4,
      sym__value,
      sym_dictionary,
      sym_list,
      sym_string,
  [75] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 3,
      sym__quoted_string,
      sym__non_quoted_string,
      sym__link_string,
    STATE(39), 4,
      sym__value,
      sym_dictionary,
      sym_list,
      sym_string,
  [96] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 3,
      sym__quoted_string,
      sym__non_quoted_string,
      sym__link_string,
    STATE(37), 4,
      sym__value,
      sym_dictionary,
      sym_list,
      sym_string,
  [117] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 3,
      sym__quoted_string,
      sym__non_quoted_string,
      sym__link_string,
    STATE(32), 4,
      sym__value,
      sym_dictionary,
      sym_list,
      sym_string,
  [138] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    STATE(31), 1,
      sym_key,
    STATE(34), 1,
      sym__wildcard_segment,
    ACTIONS(23), 2,
      sym_wildcard,
      sym_identifier_segment,
    STATE(8), 2,
      sym_pair,
      aux_sym_source_file_repeat1,
  [159] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(26), 1,
      anon_sym_RBRACE,
    STATE(30), 1,
      sym_string,
    STATE(10), 2,
      sym_inner_pair,
      aux_sym_dictionary_repeat1,
    ACTIONS(15), 3,
      sym__quoted_string,
      sym__non_quoted_string,
      sym__link_string,
  [178] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(28), 1,
      anon_sym_RBRACE,
    STATE(30), 1,
      sym_string,
    STATE(10), 2,
      sym_inner_pair,
      aux_sym_dictionary_repeat1,
    ACTIONS(30), 3,
      sym__quoted_string,
      sym__non_quoted_string,
      sym__link_string,
  [197] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    STATE(30), 1,
      sym_string,
    STATE(9), 2,
      sym_inner_pair,
      aux_sym_dictionary_repeat1,
    ACTIONS(15), 3,
      sym__quoted_string,
      sym__non_quoted_string,
      sym__link_string,
  [216] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    STATE(31), 1,
      sym_key,
    STATE(34), 1,
      sym__wildcard_segment,
    ACTIONS(7), 2,
      sym_wildcard,
      sym_identifier_segment,
    STATE(8), 2,
      sym_pair,
      aux_sym_source_file_repeat1,
  [237] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 5,
      anon_sym_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [248] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_DOT,
    STATE(16), 1,
      aux_sym_wildcard_string_repeat1,
    ACTIONS(39), 2,
      anon_sym_EQ,
      anon_sym_PLUS_EQ,
  [262] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(17), 1,
      sym__wildcard_segment,
    STATE(33), 1,
      sym_wildcard_string,
    ACTIONS(43), 2,
      sym_wildcard,
      sym_identifier_segment,
  [276] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_DOT,
    STATE(16), 1,
      aux_sym_wildcard_string_repeat1,
    ACTIONS(45), 2,
      anon_sym_EQ,
      anon_sym_PLUS_EQ,
  [290] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_DOT,
    STATE(14), 1,
      aux_sym_wildcard_string_repeat1,
    ACTIONS(50), 2,
      anon_sym_EQ,
      anon_sym_PLUS_EQ,
  [304] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 1,
      anon_sym_RBRACE,
    ACTIONS(54), 3,
      sym__quoted_string,
      sym__non_quoted_string,
      sym__link_string,
  [316] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      anon_sym_RPAREN,
    ACTIONS(58), 1,
      anon_sym_COMMA,
    STATE(24), 1,
      aux_sym__elements_repeat1,
  [329] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 3,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [338] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 3,
      ts_builtin_sym_end,
      sym_wildcard,
      sym_identifier_segment,
  [347] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 3,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [356] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(38), 1,
      sym__wildcard_segment,
    ACTIONS(66), 2,
      sym_wildcard,
      sym_identifier_segment,
  [367] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_RPAREN,
    ACTIONS(68), 1,
      anon_sym_COMMA,
    STATE(29), 1,
      aux_sym__elements_repeat1,
  [380] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(27), 1,
      sym__wildcard_segment,
    ACTIONS(70), 2,
      sym_wildcard,
      sym_identifier_segment,
  [391] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 3,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [400] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 3,
      anon_sym_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DOT,
  [409] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 3,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [418] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 1,
      anon_sym_RPAREN,
    ACTIONS(78), 1,
      anon_sym_COMMA,
    STATE(29), 1,
      aux_sym__elements_repeat1,
  [431] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 2,
      anon_sym_EQ,
      anon_sym_PLUS_EQ,
  [439] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 2,
      anon_sym_EQ,
      anon_sym_PLUS_EQ,
  [447] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [455] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 2,
      anon_sym_EQ,
      anon_sym_PLUS_EQ,
  [463] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_DOT,
  [470] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      ts_builtin_sym_end,
  [477] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      anon_sym_RPAREN,
  [484] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_SEMI,
  [491] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym_DOT,
  [498] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      anon_sym_SEMI,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 27,
  [SMALL_STATE(4)] = 51,
  [SMALL_STATE(5)] = 75,
  [SMALL_STATE(6)] = 96,
  [SMALL_STATE(7)] = 117,
  [SMALL_STATE(8)] = 138,
  [SMALL_STATE(9)] = 159,
  [SMALL_STATE(10)] = 178,
  [SMALL_STATE(11)] = 197,
  [SMALL_STATE(12)] = 216,
  [SMALL_STATE(13)] = 237,
  [SMALL_STATE(14)] = 248,
  [SMALL_STATE(15)] = 262,
  [SMALL_STATE(16)] = 276,
  [SMALL_STATE(17)] = 290,
  [SMALL_STATE(18)] = 304,
  [SMALL_STATE(19)] = 316,
  [SMALL_STATE(20)] = 329,
  [SMALL_STATE(21)] = 338,
  [SMALL_STATE(22)] = 347,
  [SMALL_STATE(23)] = 356,
  [SMALL_STATE(24)] = 367,
  [SMALL_STATE(25)] = 380,
  [SMALL_STATE(26)] = 391,
  [SMALL_STATE(27)] = 400,
  [SMALL_STATE(28)] = 409,
  [SMALL_STATE(29)] = 418,
  [SMALL_STATE(30)] = 431,
  [SMALL_STATE(31)] = 439,
  [SMALL_STATE(32)] = 447,
  [SMALL_STATE(33)] = 455,
  [SMALL_STATE(34)] = 463,
  [SMALL_STATE(35)] = 470,
  [SMALL_STATE(36)] = 477,
  [SMALL_STATE(37)] = 484,
  [SMALL_STATE(38)] = 491,
  [SMALL_STATE(39)] = 498,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__elements, 2, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__elements, 3, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dictionary_repeat1, 2, 0, 0),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_dictionary_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wildcard_string, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_wildcard_string_repeat1, 2, 0, 0),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_wildcard_string_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wildcard_string, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inner_pair, 4, 0, 1),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inner_pair, 4, 0, 1),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__elements, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 4, 0, 1),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dictionary, 3, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dictionary, 2, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__elements_repeat1, 2, 0, 0),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__elements_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key, 5, 0, 2),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [89] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_brazil_app_config(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "brazil_app_config",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
